# Generated by Django 5.2.15 on 2026-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadores',
            name='denominacion_indicador',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
