# Generated by Django 5.2.15 on 2026-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_indicadores_denominacion_indicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadores',
            name='fuente',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
