# Generated by Django 5.2.15 on 2026-06-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_irpd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irpd',
            old_name='codigo',
            new_name='criterio',
        ),
    ]
