# Generated by Django 5.2.15 on 2026-06-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_historicalindicadores_denominacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicadores',
            name='denominacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='denominacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
