# Generated by Django 5.2.15 on 2026-06-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_historicalindicadores_denominacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalindicadores',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Indicador', 'verbose_name_plural': 'historical Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='historicalirpd',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical IRPD', 'verbose_name_plural': 'historical IRPDs'},
        ),
        migrations.AlterModelOptions(
            name='indicadores',
            options={'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='irpd',
            options={'verbose_name': 'IRPD', 'verbose_name_plural': 'IRPDs'},
        ),
    ]
