# Generated by Django 5.2.15 on 2026-06-22 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_historicalindicadores_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalindicadores',
            old_name='descripcion',
            new_name='descricion',
        ),
        migrations.RenameField(
            model_name='historicalindicadores',
            old_name='fuente',
            new_name='fonte',
        ),
        migrations.RenameField(
            model_name='indicadores',
            old_name='descripcion',
            new_name='descricion',
        ),
        migrations.RenameField(
            model_name='indicadores',
            old_name='fuente',
            new_name='fonte',
        ),
        migrations.AddField(
            model_name='historicalirpd',
            name='descricion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irpd',
            name='descricion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicadores',
            name='denominacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='denominacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='irpd',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='irpd',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
