# Generated by Django 5.2.15 on 2026-06-22 13:46

import django.db.models.deletion
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_historicalresponsables_responsables'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicadores',
            name='responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, default=gestion.models.get_responsable_por_defecto, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.responsables'),
        ),
        migrations.AddField(
            model_name='indicadores',
            name='responsable',
            field=models.ForeignKey(default=gestion.models.get_responsable_por_defecto, on_delete=django.db.models.deletion.PROTECT, related_name='indicadores', to='gestion.responsables'),
        ),
    ]
