# Generated by Django 5.2.15 on 2026-06-23 08:41

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_historicalindicadores_responsable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigos',
            options={'verbose_name': 'Código', 'verbose_name_plural': 'Códigos'},
        ),
        migrations.AlterModelOptions(
            name='historicalcodigos',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Código', 'verbose_name_plural': 'historical Códigos'},
        ),
        migrations.AlterModelOptions(
            name='historicalresponsables',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Responsable', 'verbose_name_plural': 'historical Responsables'},
        ),
        migrations.AlterModelOptions(
            name='historicaltitulos',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Título', 'verbose_name_plural': 'historical Títulos'},
        ),
        migrations.AlterModelOptions(
            name='responsables',
            options={'verbose_name': 'Responsable', 'verbose_name_plural': 'Responsables'},
        ),
        migrations.AlterModelOptions(
            name='titulos',
            options={'verbose_name': 'Título', 'verbose_name_plural': 'Títulos'},
        ),
        migrations.AddField(
            model_name='indicadores',
            name='centros',
            field=models.ManyToManyField(blank=True, related_name='indicadores', to='gestion.centros'),
        ),
        migrations.AddField(
            model_name='indicadores',
            name='titulos',
            field=models.ManyToManyField(blank=True, related_name='indicadores', to='gestion.titulos'),
        ),
        migrations.AlterField(
            model_name='historicalseguimentos',
            name='curso_academico',
            field=models.CharField(choices=gestion.models.generar_curso_choices, help_text='Curso académico o que pertencen os datos (non o curso no que se introducen)', max_length=100),
        ),
        migrations.AlterField(
            model_name='seguimentos',
            name='curso_academico',
            field=models.CharField(choices=gestion.models.generar_curso_choices, help_text='Curso académico o que pertencen os datos (non o curso no que se introducen)', max_length=100),
        ),
    ]
