# Generated by Django 5.2.15 on 2026-06-25 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_historicalseguimentos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalseguimentos',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Seguimento do Centro', 'verbose_name_plural': 'historical Seguimentos do Centro'},
        ),
        migrations.AlterModelOptions(
            name='historicalseguimentostitulos',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Seguimento do Título', 'verbose_name_plural': 'historical Seguimentos do Título'},
        ),
        migrations.AlterModelOptions(
            name='seguimentos',
            options={'verbose_name': 'Seguimento do Centro', 'verbose_name_plural': 'Seguimentos do Centro'},
        ),
        migrations.AlterModelOptions(
            name='seguimentostitulos',
            options={'verbose_name': 'Seguimento do Título', 'verbose_name_plural': 'Seguimentos do Título'},
        ),
        migrations.AlterField(
            model_name='historicalseguimentos',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, dous anos despois da finalización do curso'),
        ),
        migrations.AlterField(
            model_name='historicalseguimentostitulos',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, dous anos despois da finalización do curso'),
        ),
        migrations.AlterField(
            model_name='seguimentos',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, dous anos despois da finalización do curso'),
        ),
        migrations.AlterField(
            model_name='seguimentostitulos',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, dous anos despois da finalización do curso'),
        ),
        migrations.AlterField(
            model_name='seguimentostitulos',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimentosTitulo', to='gestion.titulos'),
        ),
    ]
