# Generated by Django 5.2.15 on 2026-06-25 13:11

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_historicalseguimentos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalseguimentos',
            name='curso_academico',
        ),
        migrations.RemoveField(
            model_name='historicalseguimentostitulos',
            name='curso_academico',
        ),
        migrations.RemoveField(
            model_name='seguimentos',
            name='curso_academico',
        ),
        migrations.RemoveField(
            model_name='seguimentostitulos',
            name='curso_academico',
        ),
        migrations.AddField(
            model_name='historicalseguimentos',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, default='23/24', help_text='Origen dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalseguimentostitulos',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, default='23/24', help_text='Origen dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seguimentos',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, default='23/24', help_text='Origen dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seguimentostitulos',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, default='23/24', help_text='Origen dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalseguimentos',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, ano e medio despóis da finalización do curso'),
        ),
        migrations.AlterField(
            model_name='historicalseguimentostitulos',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, ano e medio despóis da finalización do curso'),
        ),
        migrations.AlterField(
            model_name='seguimentos',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, ano e medio despóis da finalización do curso'),
        ),
        migrations.AlterField(
            model_name='seguimentostitulos',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, ano e medio despóis da finalización do curso'),
        ),
    ]
