# Generated by Django 5.2.15 on 2026-06-26 07:25

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_remove_historicalseguimentos_curso_academico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalirpd',
            name='estandar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irpd',
            name='estandar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicadores',
            name='denominacion',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='historicalseguimentos',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, ano e medio despóis da finalización do curso', verbose_name='Data límite para a introducción dos datos'),
        ),
        migrations.AlterField(
            model_name='historicalseguimentos',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, help_text='Curso de orixe dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos (curso):'),
        ),
        migrations.AlterField(
            model_name='historicalseguimentostitulos',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, ano e medio despóis da finalización do curso', verbose_name='Data límite para a introducción dos datos'),
        ),
        migrations.AlterField(
            model_name='historicalseguimentostitulos',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, help_text='Curso de orixe dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos (curso):'),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='denominacion',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='seguimentos',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, ano e medio despóis da finalización do curso', verbose_name='Data límite para a introducción dos datos'),
        ),
        migrations.AlterField(
            model_name='seguimentos',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, help_text='Curso de orixe dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos (curso):'),
        ),
        migrations.AlterField(
            model_name='seguimentostitulos',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, ano e medio despóis da finalización do curso', verbose_name='Data límite para a introducción dos datos'),
        ),
        migrations.AlterField(
            model_name='seguimentostitulos',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, help_text='Curso de orixe dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos (curso):'),
        ),
    ]
