# Generated by Django 5.2.15 on 2026-06-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_historicalirpd_estandar_irpd_estandar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centros',
            name='equipo_decanal_directivo',
            field=models.URLField(default='https://www.uvigo.gal/default', help_text='Enlace á páxina do equipo decanal ou directivo', verbose_name='Equipo Decanal/Directivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcentros',
            name='equipo_decanal_directivo',
            field=models.URLField(default='https://www.uvigo.gal/default', help_text='Enlace á páxina do equipo decanal ou directivo', verbose_name='Equipo Decanal/Directivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaltitulos',
            name='tipo',
            field=models.CharField(choices=[('grao', 'Grao'), ('máster', 'Máster')], max_length=10),
        ),
        migrations.AlterField(
            model_name='titulos',
            name='tipo',
            field=models.CharField(choices=[('grao', 'Grao'), ('máster', 'Máster')], max_length=10),
        ),
    ]
