# Generated by Django 5.2.15 on 2026-06-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_centros_equipo_decanal_directivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigos',
            name='mec',
        ),
        migrations.RemoveField(
            model_name='historicalcodigos',
            name='mec',
        ),
    ]
