# Generated by Django 5.2.15 on 2026-06-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_remove_codigos_mec_remove_historicalcodigos_mec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalseguimentos',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Seguimento do Centro', 'verbose_name_plural': 'historical Seguimento dos Centro'},
        ),
        migrations.AlterModelOptions(
            name='historicalseguimentostitulos',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Seguimento do Título', 'verbose_name_plural': 'historical Seguimento dos Títulos'},
        ),
        migrations.AlterModelOptions(
            name='seguimentos',
            options={'verbose_name': 'Seguimento do Centro', 'verbose_name_plural': 'Seguimento dos Centro'},
        ),
        migrations.AlterModelOptions(
            name='seguimentostitulos',
            options={'verbose_name': 'Seguimento do Título', 'verbose_name_plural': 'Seguimento dos Títulos'},
        ),
        migrations.AddField(
            model_name='historicalseguimentos',
            name='tipo_indicador',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('estratexico', 'Estratéxico')], default='institucional', max_length=20, verbose_name='Tipo de Indicador'),
        ),
        migrations.AddField(
            model_name='historicalseguimentostitulos',
            name='tipo_indicador',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('estratexico', 'Estratéxico')], default='institucional', max_length=20, verbose_name='Tipo de Indicador'),
        ),
        migrations.AddField(
            model_name='seguimentos',
            name='tipo_indicador',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('estratexico', 'Estratéxico')], default='institucional', max_length=20, verbose_name='Tipo de Indicador'),
        ),
        migrations.AddField(
            model_name='seguimentostitulos',
            name='tipo_indicador',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('estratexico', 'Estratéxico')], default='institucional', max_length=20, verbose_name='Tipo de Indicador'),
        ),
    ]
