# Generated by Django 5.2.15 on 2026-06-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_alter_historicalseguimentos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalseguimentos',
            name='tipo_indicador',
        ),
        migrations.RemoveField(
            model_name='historicalseguimentostitulos',
            name='tipo_indicador',
        ),
        migrations.RemoveField(
            model_name='seguimentos',
            name='tipo_indicador',
        ),
        migrations.RemoveField(
            model_name='seguimentostitulos',
            name='tipo_indicador',
        ),
        migrations.AddField(
            model_name='historicalindicadores',
            name='tipo_indicador',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('estratexico', 'Estratégico')], default='institucional', max_length=20, verbose_name='Tipo de Indicador'),
        ),
        migrations.AddField(
            model_name='indicadores',
            name='tipo_indicador',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('estratexico', 'Estratégico')], default='institucional', max_length=20, verbose_name='Tipo de Indicador'),
        ),
    ]
