# Generated by Django 5.2.15 on 2026-06-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_remove_historicalseguimentos_tipo_indicador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalindicadores',
            name='denominacion_indicador',
        ),
        migrations.RemoveField(
            model_name='indicadores',
            name='denominacion_indicador',
        ),
        migrations.AddField(
            model_name='historicalindicadores',
            name='procedemento_asociado',
            field=models.CharField(default='prodedemento', max_length=255, verbose_name='Procedemento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadores',
            name='procedemento_asociado',
            field=models.CharField(default='procedemento', max_length=255, verbose_name='Procedemento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalindicadores',
            name='denominacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='denominacion',
            field=models.CharField(max_length=255),
        ),
    ]
