# Generated by Django 5.2.15 on 2026-06-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_remove_historicalindicadores_denominacion_indicador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicadores',
            name='procedemento_asociado',
            field=models.CharField(max_length=255, verbose_name='Procedemento Asociado'),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='procedemento_asociado',
            field=models.CharField(max_length=255, verbose_name='Procedemento Asociado'),
        ),
    ]
