# Generated by Django 5.2.15 on 2026-06-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_alter_historicalindicadores_procedemento_asociado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicadores',
            name='codigo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalindicadores',
            name='tipo_indicador',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('estratexico', 'Estratégico'), ('calidade', 'Calidade')], default='institucional', max_length=20, verbose_name='Tipo de Indicador'),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='codigo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='tipo_indicador',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('estratexico', 'Estratégico'), ('calidade', 'Calidade')], default='institucional', max_length=20, verbose_name='Tipo de Indicador'),
        ),
    ]
