# Generated by Django 5.2.15 on 2026-06-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_alter_historicalindicadores_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicadores',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
