# Generated by Django 5.2.15 on 2026-07-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_alter_historicalindicadores_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigos',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcodigos',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
