# Generated by Django 5.2.15 on 2026-07-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_codigos_notas_historicalcodigos_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='xescampus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcodigos',
            name='xescampus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
