# Generated by Django 5.2.15 on 2026-07-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_alter_codigos_xescampus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='ruct',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcodigos',
            name='ruct',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
