# Generated by Django 5.2.15 on 2026-07-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_alter_codigos_ruct_alter_historicalcodigos_ruct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='estudio_sigma',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcodigos',
            name='estudio_sigma',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
