# Generated by Django 5.2.15 on 2026-07-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_alter_codigos_estudio_sigma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codigos', to='gestion.titulos', unique=True),
        ),
    ]
