# Generated by Django 5.2.15 on 2026-07-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0032_alter_codigos_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='titulo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='codigos', to='gestion.titulos'),
        ),
    ]
