# Generated by Django 5.2.15 on 2026-07-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0033_alter_codigos_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centros',
            old_name='direccion_webb',
            new_name='direccion_web',
        ),
        migrations.RenameField(
            model_name='historicalcentros',
            old_name='direccion_webb',
            new_name='direccion_web',
        ),
        migrations.AlterField(
            model_name='historicaltitulos',
            name='tipo',
            field=models.CharField(choices=[('grao', 'Grao'), ('dobre grao', 'Dobre Grao'), ('máster', 'Máster')], max_length=10),
        ),
        migrations.AlterField(
            model_name='titulos',
            name='tipo',
            field=models.CharField(choices=[('grao', 'Grao'), ('dobre grao', 'Dobre Grao'), ('máster', 'Máster')], max_length=10),
        ),
    ]
