# Generated by Django 5.2.15 on 2026-07-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0034_rename_direccion_webb_centros_direccion_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='titulo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='gestion.titulos'),
        ),
    ]
