# Generated by Django 5.2.15 on 2026-07-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0035_alter_codigos_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsables',
            options={'ordering': ('denominacion',), 'verbose_name': 'Responsable', 'verbose_name_plural': 'Responsables'},
        ),
        migrations.AddField(
            model_name='historicalresponsables',
            name='descricion',
            field=models.TextField(blank=True, null=True, verbose_name='Descrición'),
        ),
        migrations.AddField(
            model_name='responsables',
            name='descricion',
            field=models.TextField(blank=True, null=True, verbose_name='Descrición'),
        ),
    ]
