# Generated by Django 5.2.15 on 2026-07-10 11:01

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0036_alter_responsables_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centros',
            options={'ordering': ('denominacion',), 'verbose_name': 'Centro', 'verbose_name_plural': 'Centros'},
        ),
        migrations.AlterModelOptions(
            name='historicallocalizadores',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Localización', 'verbose_name_plural': 'historical Localizaciones'},
        ),
        migrations.AlterModelOptions(
            name='indicadores',
            options={'ordering': ('codigo', 'denominacion'), 'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='irpd',
            options={'ordering': ('criterio',), 'verbose_name': 'IRPD', 'verbose_name_plural': 'IRPDs'},
        ),
        migrations.AlterModelOptions(
            name='localizadores',
            options={'verbose_name': 'Localización', 'verbose_name_plural': 'Localizaciones'},
        ),
        migrations.AlterModelOptions(
            name='seguimentos',
            options={'ordering': ('indicador__denominacion',), 'verbose_name': 'Seguimento do Centro', 'verbose_name_plural': 'Seguimento dos Centro'},
        ),
        migrations.AlterModelOptions(
            name='seguimentostitulos',
            options={'ordering': ('indicador__denominacion',), 'verbose_name': 'Seguimento do Título', 'verbose_name_plural': 'Seguimento dos Títulos'},
        ),
        migrations.AlterModelOptions(
            name='titulos',
            options={'ordering': ('denominacion',), 'verbose_name': 'Título', 'verbose_name_plural': 'Títulos'},
        ),
        migrations.AlterField(
            model_name='historicalindicadores',
            name='sentido',
            field=models.CharField(choices=[('positivo', 'A máis, mellor'), ('negativo', 'A menos, mellor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalindicadores',
            name='tipo_indicador',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('estratexico', 'Estratéxico'), ('calidade', 'Calidade')], default='institucional', max_length=20, verbose_name='Tipo de Indicador'),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='sentido',
            field=models.CharField(choices=[('positivo', 'A máis, mellor'), ('negativo', 'A menos, mellor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='tipo_indicador',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('estratexico', 'Estratéxico'), ('calidade', 'Calidade')], default='institucional', max_length=20, verbose_name='Tipo de Indicador'),
        ),
        migrations.CreateModel(
            name='AvaliacionsPdis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
                ('totales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de PDIs avaliados')),
                ('excelentes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de PDIs excelentes')),
                ('notables', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de PDIs notables')),
                ('favorables', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de PDIs favorables')),
                ('desfavorables', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de PDIs desfavorables')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='gestion.indicadores')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('titulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacion_pdis', to='gestion.titulos')),
            ],
            options={
                'verbose_name': 'Avaliación',
                'verbose_name_plural': 'Avaliacións',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAvaliacionsPdis',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('creacion', models.DateTimeField(blank=True, editable=False)),
                ('actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('totales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de PDIs avaliados')),
                ('excelentes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de PDIs excelentes')),
                ('notables', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de PDIs notables')),
                ('favorables', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de PDIs favorables')),
                ('desfavorables', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de PDIs desfavorables')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.indicadores')),
                ('modificado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('titulo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.titulos')),
            ],
            options={
                'verbose_name': 'historical Avaliación',
                'verbose_name_plural': 'historical Avaliacións',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
