# Generated by Django 5.2.15 on 2026-07-10 11:10

import django.db.models.deletion
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0037_alter_centros_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacionspdis',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, default='----', help_text='Curso de orixe dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos (curso):'),
        ),
        migrations.AddField(
            model_name='historicalavaliacionspdis',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, default='----', help_text='Curso de orixe dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos (curso):'),
        ),
        migrations.AlterField(
            model_name='avaliacionspdis',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulo_avaliado', to='gestion.titulos'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacionspdis',
            unique_together={('titulo', 'orixe_datos')},
        ),
    ]
