# Generated by Django 5.2.15 on 2026-07-10 15:53

import django.core.validators
import django.db.models.deletion
import gestion.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0038_avaliacionspdis_orixe_datos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMateriasAvaliadas',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('creacion', models.DateTimeField(blank=True, editable=False)),
                ('actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('codigo', models.CharField(db_index=True, max_length=50, verbose_name='Código materia')),
                ('materia', models.CharField(max_length=255, verbose_name='Asignatura')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('titulo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.titulos')),
            ],
            options={
                'verbose_name': 'historical Materia Avaliada',
                'verbose_name_plural': 'historical Materias Avaliadas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MateriasAvaliadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código materia')),
                ('materia', models.CharField(max_length=255, verbose_name='Asignatura')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='gestion.titulos')),
            ],
            options={
                'verbose_name': 'Materia Avaliada',
                'verbose_name_plural': 'Materias Avaliadas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSeguementoMaterias',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('creacion', models.DateTimeField(blank=True, editable=False)),
                ('actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('orixe_datos', models.CharField(choices=gestion.models.generar_curso_choices, help_text='Curso de orixe dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos (curso):')),
                ('meta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_meta', models.CharField(choices=[('numero', 'Número'), ('porcentaje', 'Porcentaje')], max_length=10)),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_limite', models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, ano e medio despóis da finalización do curso', verbose_name='Data límite para a introducción dos datos')),
                ('valoracion_final', models.BooleanField(blank=True, null=True)),
                ('observacions', models.TextField(blank=True, null=True)),
                ('taxa', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa (%)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.indicadores')),
                ('modificado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.materiasavaliadas')),
            ],
            options={
                'verbose_name': 'historical Seguemento de Materia',
                'verbose_name_plural': 'historical Seguementos de Materias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='indicadores',
            name='materia',
            field=models.ManyToManyField(blank=True, related_name='indicadores', to='gestion.materiasavaliadas'),
        ),
        migrations.CreateModel(
            name='SeguementoMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
                ('orixe_datos', models.CharField(choices=gestion.models.generar_curso_choices, help_text='Curso de orixe dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos (curso):')),
                ('meta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_meta', models.CharField(choices=[('numero', 'Número'), ('porcentaje', 'Porcentaje')], max_length=10)),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_limite', models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, ano e medio despóis da finalización do curso', verbose_name='Data límite para a introducción dos datos')),
                ('valoracion_final', models.BooleanField(blank=True, null=True)),
                ('observacions', models.TextField(blank=True, null=True)),
                ('taxa', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa (%)')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='gestion.indicadores')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguementos', to='gestion.materiasavaliadas')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguemento de Materia',
                'verbose_name_plural': 'Seguementos de Materias',
                'unique_together': {('materia', 'orixe_datos')},
            },
        ),
    ]
