# Generated by Django 5.2.15 on 2026-07-10 16:38

import django.db.models.deletion
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0039_historicalmateriasavaliadas_materiasavaliadas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacionspdis',
            options={'verbose_name': 'Avaliación PDI', 'verbose_name_plural': 'Avaliacións PDI'},
        ),
        migrations.AlterModelOptions(
            name='historicalavaliacionspdis',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Avaliación PDI', 'verbose_name_plural': 'historical Avaliacións PDI'},
        ),
        migrations.AddField(
            model_name='avaliacionspdis',
            name='data_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Data límite para a introducción dos datos'),
        ),
        migrations.AddField(
            model_name='historicalavaliacionspdis',
            name='data_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Data límite para a introducción dos datos'),
        ),
        migrations.AlterField(
            model_name='avaliacionspdis',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacions_pdis', to='gestion.indicadores'),
        ),
        migrations.AlterField(
            model_name='avaliacionspdis',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, help_text='Curso de orixe dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos (curso):'),
        ),
        migrations.AlterField(
            model_name='avaliacionspdis',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacion_pdis', to='gestion.titulos'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacionspdis',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, help_text='Curso de orixe dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos (curso):'),
        ),
    ]
