# Generated by Django 5.2.15 on 2026-07-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0040_alter_avaliacionspdis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalavaliacionspdis',
            name='indicador',
        ),
        migrations.RemoveField(
            model_name='avaliacionspdis',
            name='indicador',
        ),
        migrations.AddField(
            model_name='avaliacionspdis',
            name='indicador',
            field=models.ManyToManyField(blank=True, related_name='avaliacions_pdis', to='gestion.indicadores'),
        ),
    ]
