# Generated by Django 5.2.15 on 2026-07-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0041_remove_historicalavaliacionspdis_indicador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacionspdis',
            name='indicador',
            field=models.ManyToManyField(blank=True, help_text='Cubrir só en caso de que o indicador sexa diferente de <strong>"Resultados do PDI avaliado"</strong>, co procedemento asociado "<strong>PE-02 Xestión de PDI</strong>"', related_name='avaliacions_pdis', to='gestion.indicadores'),
        ),
    ]
