# Generated by Django 5.2.15 on 2026-07-13 18:50

import django.core.validators
import django.db.models.deletion
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0042_alter_avaliacionspdis_indicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalseguementomaterias',
            name='data_limite',
        ),
        migrations.RemoveField(
            model_name='historicalseguementomaterias',
            name='observacions',
        ),
        migrations.RemoveField(
            model_name='historicalseguementomaterias',
            name='tipo_meta',
        ),
        migrations.RemoveField(
            model_name='historicalseguementomaterias',
            name='valoracion_final',
        ),
        migrations.AlterUniqueTogether(
            name='seguementomaterias',
            unique_together={('materia', 'indicador', 'orixe_datos')},
        ),
        migrations.AlterField(
            model_name='avaliacionspdis',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, help_text='Curso de orixe dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos (curso)'),
        ),
        migrations.AlterField(
            model_name='avaliacionspdis',
            name='totales',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total PDIs'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacionspdis',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, help_text='Curso de orixe dos datos (non o curso no que se introducen)', max_length=10, verbose_name='Orixe dos datos (curso)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacionspdis',
            name='totales',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total PDIs'),
        ),
        migrations.AlterField(
            model_name='historicalseguementomaterias',
            name='meta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Meta (%)'),
        ),
        migrations.AlterField(
            model_name='historicalseguementomaterias',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, max_length=10, verbose_name='Orixe dos datos (curso)'),
        ),
        migrations.AlterField(
            model_name='historicalseguementomaterias',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resultado (%)'),
        ),
        migrations.AlterField(
            model_name='historicalseguementomaterias',
            name='taxa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa (%)'),
        ),
        migrations.AlterField(
            model_name='seguementomaterias',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguementos_materias', to='gestion.indicadores'),
        ),
        migrations.AlterField(
            model_name='seguementomaterias',
            name='meta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Meta (%)'),
        ),
        migrations.AlterField(
            model_name='seguementomaterias',
            name='orixe_datos',
            field=models.CharField(choices=gestion.models.generar_curso_choices, max_length=10, verbose_name='Orixe dos datos (curso)'),
        ),
        migrations.AlterField(
            model_name='seguementomaterias',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resultado (%)'),
        ),
        migrations.AlterField(
            model_name='seguementomaterias',
            name='taxa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa (%)'),
        ),
        migrations.RemoveField(
            model_name='seguementomaterias',
            name='data_limite',
        ),
        migrations.RemoveField(
            model_name='seguementomaterias',
            name='observacions',
        ),
        migrations.RemoveField(
            model_name='seguementomaterias',
            name='tipo_meta',
        ),
        migrations.RemoveField(
            model_name='seguementomaterias',
            name='valoracion_final',
        ),
    ]
