# Generated by Django 5.2.15 on 2026-07-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0043_remove_historicalseguementomaterias_data_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseguementomaterias',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, ano e medio despóis da finalización do curso', null=True, verbose_name='Data límite para a introducción dos datos'),
        ),
        migrations.AddField(
            model_name='seguementomaterias',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Calculada automaticamente: 31 de decembro, ano e medio despóis da finalización do curso', null=True, verbose_name='Data límite para a introducción dos datos'),
        ),
    ]
